version: 2

jobs:

  build:
    working_directory: ~/Font-Awesome

    docker:
      - image: ncino/ci-sfdx:latest

    environment:
      DEPLOY_TOOLKIT: ~/python-deploy-toolkit
      FAILURE_FILE: /tmp/build_failures.txt
      GITHUB_REPO: Font-Awesome

    steps:
      - checkout

      - run:
          name: Checkout python-deploy-toolkit
          command: git clone git@github.com:ncino/python-deploy-toolkit.git ~/python-deploy-toolkit

      - run:
          name: Install python-deploy-toolkit
          command: cd ~/python-deploy-toolkit && npm install -g

      - run:
          name: sfdeploy -d report_build_info
          command: sfdeploy -d report_build_info -lt off || ( touch $FAILURE_FILE && exit 1 )

      - run:
          name: Bundle Install
          command: source /etc/profile.d/rvm.sh && rvm use 2.2.7 && bundle install || ( touch $FAILURE_FILE && exit 1 )

      - run:
          name: Run npm install
          command: npm install || ( touch $FAILURE_FILE && exit 1 )

      - run:
          name: Run jekyll build
          command: source /etc/profile.d/rvm.sh && rvm use 2.2.7 bundle exec jekyll build || ( touch $FAILURE_FILE && exit 1 )

      - deploy:
          name: Build the release and deploy to github
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              build-release
            fi

      - run:
          name: Build notifications
          command: ~/python-deploy-toolkit/scripts/build_notifications.py
          when: always

      - store_artifacts:
          path: ~/Font-Awesome/dist/assets/font-awesome/font-awesome.zip
          destination: font-awesome.resource
