version: 2

jobs:

  build:
    working_directory: ~/Font-Awesome

    docker:
      - image: ncino/ci-sfdx:1.1.1a

    environment:
      DEPLOY_TOOLKIT: ~/python-deploy-toolkit
      FAILURE_FILE: /tmp/build_failures.txt
      GITHUB_REPO: Font-Awesome

    steps:
      - checkout

      - run:
          name: Checkout python-deploy-toolkit
          command: git clone git@github.com:ncino/python-deploy-toolkit.git $DEPLOY_TOOLKIT

      - run:
          name: Install python-deploy-toolkit
          command: cd $DEPLOY_TOOLKIT && npm install -g

      - run:
          name: Get github-release
          command: go get github.com/aktau/github-release || ( touch $FAILURE_FILE && exit 1 )

      - run:
          name: sfdeploy -d report_build_info
          command: sfdeploy -d report_build_info -lt off || ( touch $FAILURE_FILE && exit 1 )

      - run:
          name: Bundle Install
          command: bundle install || ( touch $FAILURE_FILE && exit 1 )

      - run:
          name: Run npm install
          command: npm install || ( touch $FAILURE_FILE && exit 1 )

      - run:
          name: Run jekyll build
          command: bundle exec jekyll build || ( touch $FAILURE_FILE && exit 1 )

      - deploy:
          name: Build the release and deploy to github
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              build-release
            fi

      - run:
          name: Build notifications
          command: $DEPLOY_TOOLKIT/scripts/build_notifications.py
          when: always

      - store_artifacts:
          path: ~/Font-Awesome/dist/assets/font-awesome/font-awesome.zip
          destination: font-awesome.resource
